name: ffmpeg-example
title: Ffmpeg example with API httpserver, HTML5 cli and dashboard apps
author: Anonymous
require:
- osv.httpserver-html5-cli
- osv.httpserver-html5-gui
- osv.ffmpeg
created: 2018-06-02T22:43:08Z
